# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Exercise.create(category: "Legs", exercise_name: "Barbell Squat", reps: "12", equipment: "Barbell")
# Exercise.create(category: "Legs", exercise_name: "Hack Squat", reps: "12", equipment: "Machine")
# Exercise.create(category: "Legs", exercise_name: "Trapbar Deadlift", reps: "12", equipment: "Trap Bar")
# # Exercise.create(category: "Legs", exercise_name: "Lunge", reps: "12", equipment: "Barbell")
# # Exercise.create(category: "Legs", exercise_name: "Leg Extension", reps: "12", equipment: "Machine")
# # Exercise.create(category: "Legs", exercise_name: "RDL", reps: "12", equipment: "Barbell")
# Exercise.create(category: "Biceps", exercise_name: "Dumbbell Curl", reps: "12", equipment: "Dumbbell")
# Exercise.create(category: "Biceps", exercise_name: "Hammer Curl", reps: "12", equipment: "Dumbbell")
# Exercise.create(category: "Biceps", exercise_name: "Inverse Curl", reps: "12", equipment: "Dumbbell")
# # Exercise.create(category: "Biceps", exercise_name: "Barbell 21's", reps: "12", equipment: "Barbell")
# # Exercise.create(category: "Biceps", exercise_name: "Spider Curl", reps: "12", equipment: "Dumbbell")
# # Exercise.create(category: "Biceps", exercise_name: "Cable Curl", reps: "12", equipment: "Machine")
# Exercise.create(category: "Triceps", exercise_name: "Body Weight Dip", reps: "12", equipment: "BW")
# Exercise.create(category: "Triceps", exercise_name: "Skull Crusher", reps: "12", equipment: "EZ Bar")
# Exercise.create(category: "Triceps", exercise_name: "French Press", reps: "12", equipment: "Dumbbell")
# # Exercise.create(category: "Triceps", exercise_name: "Close Grip Bench ", reps: "12", equipment: "Barbell")
# # Exercise.create(category: "Triceps", exercise_name: "Straight Bar Cable Press ", reps: "12", equipment: "Machine")
# # Exercise.create(category: "Triceps", exercise_name: "Rope Pulls", reps: "12", equipment: "Machine")
# Exercise.create(category: "Back", exercise_name: "Wide Grip Barbell Row", reps: "12", equipment: "Barbell")
# Exercise.create(category: "Back", exercise_name: "Good Morning", reps: "12", equipment: "Barbell")
# Exercise.create(category: "Back", exercise_name: "Lat Pull Down", reps: "12", equipment: "Machine")
# Exercise.create(category: "Back", exercise_name: "Close Grip Cable Row", reps: "12", equipment: "Machine")
# # Exercise.create(category: "Back", exercise_name: "Shotgun Row", reps: "12", equipment: "Machine")
# # Exercise.create(category: "Back", exercise_name: "Kroc Row", reps: "12", equipment: "Dumbbell")
# # Exercise.create(category: "Back", exercise_name: "Chin Up", reps: "12", equipment: "BW")
# Exercise.create(category: "Shoulders", exercise_name: "Military Press", reps: "12", equipment: "Barbell")
# Exercise.create(category: "Shoulders", exercise_name: "Face Pulls", reps: "12", equipment: "Machine")
# Exercise.create(category: "Shoulders", exercise_name: "Lateral Raise", reps: "12", equipment: "Dumbbell")
# # Exercise.create(category: "Shoulders", exercise_name: "Plate Front Raise", reps: "12", equipment: "Weighted Plate")
# # Exercise.create(category: "Shoulders", exercise_name: "Shoulder Press", reps: "12", equipment: "Barbell")
# # Exercise.create(category: "Shoulders", exercise_name: "Steering Wheel", reps: "12", equipment: "Weighted Plate")
# # Exercise.create(category: "Shoulders", exercise_name: "Rear Delt Fly", reps: "12", equipment: "Dumbbell")
# Exercise.create(category: "Chest", exercise_name: "Push Up", reps: "12", equipment: "BW")
# Exercise.create(category: "Chest", exercise_name: "Incline Chest Press", reps: "12", equipment: "Barbell")
# Exercise.create(category: "Chest", exercise_name: "Flat Bench Press", reps: "12", equipment: "Barbell")
# # Exercise.create(category: "Chest", exercise_name: "Svend Plate Press", reps: "12", equipment: "Weighted Plate")
# # Exercise.create(category: "Chest", exercise_name: "Chest Fly", reps: "12", equipment: "Machine")
# # Exercise.create(category: "Chest", exercise_name: "Decline Push Up", reps: "12", equipment: "BW" )
# Exercise.create(category: "Abs", exercise_name: "Hollow Hold", reps: "12", equipment: "BW")
# Exercise.create(category: "Abs", exercise_name: "Russian Twist", reps: "12", equipment: "BW")
# Exercise.create(category: "Abs", exercise_name: "Walking Plank" , reps: "12", equipment: "BW")
Exercise.create(category: "Abs", exercise_name: "V-Up", reps: "12", equipment: "BW")
Exercise.create(category: "Abs", exercise_name: "Prone Cobra", reps: "12", equipment: "BW")
Exercise.create(category: "Abs", exercise_name: "Side Plank", reps: "12", equipment: "BW")
Exercise.create(category: "Abs", exercise_name: "Reverse Crunch", reps: "12", equipment: "BW")


WorkoutExercise.create(workout_id: 1, exercise_id: 13)
WorkoutExercise.create(workout_id: 1, exercise_id: 3)
WorkoutExercise.create(workout_id: 1, exercise_id: 8)
WorkoutExercise.create(workout_id: 1, exercise_id: 10)
WorkoutExercise.create(workout_id: 1, exercise_id: 15)

WorkoutExercise.create(workout_id: 2, exercise_id: 4)
WorkoutExercise.create(workout_id: 2, exercise_id: 5)
WorkoutExercise.create(workout_id: 2, exercise_id: 6)
WorkoutExercise.create(workout_id: 2, exercise_id: 7)
WorkoutExercise.create(workout_id: 2, exercise_id: 8)

WorkoutExercise.create(workout_id: 3, exercise_id: 10)
WorkoutExercise.create(workout_id: 3, exercise_id: 11)
WorkoutExercise.create(workout_id: 3, exercise_id: 12)
WorkoutExercise.create(workout_id: 3, exercise_id: 13)
WorkoutExercise.create(workout_id: 3, exercise_id: 14)

Workout.create(title: "Armed Assault", note: "All Arm Workout")
Workout.create(title: "Grand Canyon", note: "Building width through Shoulders and Back")

# when you chase failure, youre often chasing success, the tail and the head are on the same animal
